name: collager
channels:
  - r
  - defaults
dependencies:
  - jupyter=1.0.0=py36_7
  - numpy=1.17.2=py36hc73f44b_0
  - pandas=0.25.2=py36ha925a31_0
  - pillow=4.2.1=py36hdb25ab2_0
  - pip=19.3.1=py36_0
  - tqdm=4.36.1=py_0
